dist: xenail

addons:
    apt:
        packages:
            - docker-ce
jobs:
    name: "OpenCV 4.4.0 with Ubuntu 20.04"
    include:
        on:
            branch: master
        env:
            - OPENCV_VERSION="4.4.0"
        - stage: build
        script: docker build --build-arg OPENCV_VERSION=${OPENCV_VERSION} -t opencv:${OPENCV_VERSION} .
        - stage: test
        script: docker run opencv:${OPENCV_VERSION} python -c "import cv2; print(cv2.__version__)"

    name: "OpenCV 4.5.0 with Ubuntu 20.04"
    include:
        on:
            branch: master
        env:
            - OPENCV_VERSION="4.5.0"
        - stage: build
        script: docker build --build-arg OPENCV_VERSION=${OPENCV_VERSION} -t opencv:${OPENCV_VERSION} .
        - stage: test
        script: docker run opencv:${OPENCV_VERSION} python -c "import cv2; print(cv2.__version__)"
